Repository AY2425S1-CS2103T-W14-3/tp, pull requests merged in 2024-11, with the labels that each got.

#147 Make changes to MemberCard.java and DarkTheme.css
  src/main/java/hallpointer/address/ui/MemberCard.java
  src/main/resources/view/DarkTheme.css
Labels: alpha-bug

#149 Add FindSessionCommand
  src/main/java/hallpointer/address/logic/commands/FindSessionCommand.java
  src/main/java/hallpointer/address/logic/parser/FindSessionCommandParser.java
  src/main/java/hallpointer/address/logic/parser/HallPointerParser.java
  src/main/java/hallpointer/address/model/member/SessionContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Medium

#155 Add tests
  src/main/java/hallpointer/address/logic/commands/FindSessionCommand.java
  src/test/java/hallpointer/address/logic/commands/FindSessionCommandTest.java
  src/test/java/hallpointer/address/logic/parser/DeleteSessionCommandParserTest.java
  src/test/java/hallpointer/address/logic/parser/FindSessionCommandParserTest.java
Labels: type.Chore, priority.Medium, severity.Medium

#169 Fix header format issues
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.Medium, priority.Low

#227 Fix list command error
  docs/UserGuide.md
  docs/images/listCommandResult.png
Labels: alpha-bug

#228 Fix update bug
  src/main/java/hallpointer/address/logic/commands/UpdateMemberCommand.java
  src/main/java/hallpointer/address/model/HallPointer.java
  src/main/java/hallpointer/address/model/Model.java
  src/main/java/hallpointer/address/model/ModelManager.java
  src/main/java/hallpointer/address/model/member/Member.java
  src/main/java/hallpointer/address/model/member/UniqueMemberList.java
  src/test/java/hallpointer/address/model/HallPointerTest.java
  src/test/java/hallpointer/address/testutil/ModelStub.java
Labels: duplicateBug

#233 Branch fix ug
  docs/UserGuide.md
  docs/images/addCommandResult.png
  docs/images/addSessionResult.png
  docs/images/deleteMemberResult.png
  docs/images/deleteSessionResult.png
  docs/images/findTeamResult.png
  docs/images/updateCommandResult.png
  src/main/java/hallpointer/address/logic/commands/FindSessionCommand.java
  src/test/java/hallpointer/address/logic/commands/FindSessionCommandTest.java
Labels: priority.Medium, type.UserGuide

#235 Change ug for consistency
  docs/UserGuide.md
  docs/images/findSessionResult.png
Labels: type.UserGuide
