Repository AY2425S1-CS2103T-W14-3/tp, pull requests merged in 2024-10, with the labels that each got.

#43 Fix website GitHub link
  docs/_markbind/layouts/default.md
Labels: type.Bug

#44 Week 7 Task 2 - A1
  docs/images/Ui.png
Labels: priority.High

#45 Week 7 Task 3 - Create Use Cases
  docs/DeveloperGuide.md
  docs/team/qinhaichen12.md
Labels: priority.High

#47 Change README.md
  README.md
Labels: type.Chore, priority.Medium

#66 add session commands for create delete and edit
  src/main/java/hallpointer/address/logic/Messages.java
  src/main/java/hallpointer/address/logic/commands/AddSessionCommand.java
  src/main/java/hallpointer/address/logic/commands/DeleteSessionCommand.java
  src/main/java/hallpointer/address/logic/commands/EditSessionCommand.java
  src/main/java/hallpointer/address/logic/parser/AddSessionCommandParser.java
  src/main/java/hallpointer/address/logic/parser/AddressBookParser.java
  src/main/java/hallpointer/address/logic/parser/CliSyntax.java
  src/main/java/hallpointer/address/logic/parser/DeleteSessionCommandParser.java
  src/main/java/hallpointer/address/logic/parser/EditSessionCommandParser.java
  src/main/java/hallpointer/address/logic/parser/ParserUtil.java
  src/main/java/hallpointer/address/model/AddressBook.java
  src/main/java/hallpointer/address/model/Model.java
  src/main/java/hallpointer/address/model/ModelManager.java
  src/main/java/hallpointer/address/model/member/exceptions/DuplicateSessionException.java
  src/main/java/hallpointer/address/model/member/exceptions/SessionNotFoundException.java
  src/main/java/hallpointer/address/model/session/Session.java
  src/main/java/hallpointer/address/model/session/UniqueSessionList.java
  src/main/java/hallpointer/address/storage/JsonSerializableAddressBook.java
  src/test/java/hallpointer/address/logic/commands/AddMemberCommandTest.java
Labels: priority.High

#83 add unique check for adding session
  src/main/java/hallpointer/address/logic/commands/AddSessionCommand.java
  src/main/java/hallpointer/address/model/member/Member.java
  src/main/java/hallpointer/address/model/session/Session.java
Labels: priority.High

#82 Update TC and UserGuide
  docs/UserGuide.md
  src/main/java/hallpointer/address/logic/Messages.java
  src/test/java/hallpointer/address/logic/commands/AddMemberCommandTest.java
Labels: priority.High

#89 fix bug
  src/main/java/hallpointer/address/storage/JsonAdaptedSession.java
Labels: priority.High

#93 Update sample data to include sessions and points
  src/main/java/hallpointer/address/model/util/SampleDataUtil.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#101 Branch chronological sessions
  src/main/java/hallpointer/address/ui/MemberCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MemberListCard.fxml
Labels: severity.Low

#111 Add tests for delete parser
  src/test/java/hallpointer/address/logic/parser/DeleteMemberCommandParserTest.java
Labels: priority.Medium

#110 Branch edit uml
  docs/AboutUs.md
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/index.md
  docs/team/qinhaichen12.md
Labels: priority.High
